[application]
asset_dir = "assets"
sub_package = "poker-gui"

[bundle]
identifier = "com.acrilique.poker"
publisher = "Acrilique"
icon = [
    "assets/icons/16x16.png",
    "assets/icons/24x24.png",
    "assets/icons/32x32.png",
    "assets/icons/64x64.png",
    "assets/icons/256x256.png",
    "assets/icons/icon.ico",
]
category = "CasinoGame"
